# Generated by Django 5.2 on 2025-10-02 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outh', '0002_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
