# Generated by Django 5.2 on 2025-10-08 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outh', '0003_delete_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
